### ISSUE TITLE
Do not display any image in the video player

### ISSUE THREAD

**Issue by vahidsaberi** [carpediem-av/rtsp2hls#1]
I ran your project and all the steps are working properly except the image display
Do I need to make any special adjustments
![Screenshot 2022-01-26 143332](https://user-images.githubusercontent.com/4094627/151152104-14b564e1-9a64-4cee-bd30-14a531c1c2b8.jpg)
?

**Comment by carpediem-av** [comment]
Did you enter camera's RTSP-link correctly in the Configurator? You can test RTSP-links in VLC player.
Here is an example of link for Hikvision (Hiwatch) cameras:

rtsp://admin:12345@192.168.200.11:554/Streaming/Channels/101

192.168.200.11 is camera IP
admin is camera user
12345 is camera password

Maybe you forgot to include camera username and password in the link? Also make sure that the stream encoding parameters (in the settings of the camera itself) are set to H.264 format. The newer H.265 is not supported by most browsers.

**Comment by vahidsaberi** [comment]
The camera link is correct and tested in VLC player.
The live server project also saves video properly in-stream folder.
problem is in the browser that can not display the video and maybe from the Stream Process function.
You can explain more about how to install it on the server.
![Screenshot 2022-01-27 092909](https://user-images.githubusercontent.com/4094627/151300608-ed362b38-c2c7-441a-b1fe-b53191e9f4ec.jpg)

**Comment by vahidsaberi** [comment]
I had to off the H-264+
Thank you for your response

**Comment by carpediem-av** [comment]
Does the browser play video after disabling H.264+?

**Comment by vahidsaberi** [comment]
Yes, my problem was solved by disabling this option.

**Comment by carpediem-av** [comment]
Thanks for the information. Probably improved H.264+ is not compatible with browsers.

Note. You can also get a snapshot from the camera by replacing the word "player" with "image" in the http links.
